In [7]:
import tensorflow as tf

a = tf.constant([[5,2],[1,7]])
b = tf.constant([[3,5],[5,4]])

c = a - b
print(c)

tf.Tensor(
[[ 2 -3]
 [-4  3]], shape=(2, 2), dtype=int32)


In [15]:
c = c ** 2

In [16]:
tf.reduce_sum(c)

<tf.Tensor: shape=(), dtype=int32, numpy=38>

In [17]:
c * 1/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 4.5],
       [8. , 4.5]])>